FROM --platform=linux/amd64 python:3.10

# Install system wine translation layers natively
RUN apt-get update && apt-get install -y --no-install-recommends \
    wine64 \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY requirements.txt .

# Force pip to download the Windows architecture variations of your modules
RUN pip install --no-cache-dir pyinstaller
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["pyinstaller"]
